#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${APP_USER} ENCRYPTED PASSWORD '${APP_PASSWORD}';
    CREATE DATABASE ${APP_DB} WITH ENCODING 'UTF8';
    GRANT ALL PRIVILEGES ON DATABASE ${APP_DB} TO ${APP_USER};
EOSQL
